Disable pre v1.0 CWL tests.
Pre v1.0 CWL tests have been disabled to prevent exception below during Galaxy startup.

ValidationException: The CWL reference runner no longer supports pre CWL v1.0 documents. Supported versions are:
v1.0
v1.1.0-dev1 (with --enable-dev flag only)